# Generated by Django 4.0.6 on 2023-05-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='DEFAULT VALUE', max_length=50, unique=True)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=50, unique=True)),
            ],
        ),
    ]
